# -*- coding: utf-8 -*-
"""LabPractical3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NI4vHS92SfgdxiIkwm8yQr-mJfd5tZje
"""

import pandas as pd
import numpy as np

csv=pd.read_csv("/content/drive/MyDrive/AI-ML Practical 3/train.csv")

print("\nHead : ",csv.head(),"\n")
print("\nShape : ",csv.shape,"\n")
print("\nInfo : ",csv.info,"\n")
print("\nDescripe : ",csv.describe(),"\n")

csv1=csv.copy()
csv1.dropna(axis=0)
print(csv1)

print("\nHead : ",csv1.head(),"\n")
print("\nShape : ",csv1.shape,"\n")
print("\nInfo : ",csv1.info,"\n")
print("\nDescripe : ",csv1.describe(),"\n")

csv["Cabin"].fillna(csv["Cabin"].mode()[0], inplace=True)
csv["Age"].fillna(csv["Age"].mean().round().astype(int), inplace=True)
csv["Embarked"].fillna(csv["Embarked"].mode()[0], inplace=True)
csv.to_csv('/content/drive/MyDrive/AI-ML Practical 3/train2.csv', index=False)
print(csv)